// Auto-generated by Supabase CLI. Do not edit manually.
// Run: npx supabase gen types typescript --local > src/lib/supabase/types.ts
export type Database = Record<string, never>;

// ============================================================================
// Hand-written application types for the run sheet
// ============================================================================

export type UserRole = 'practice_manager' | 'receptionist' | 'clinician';
export type RoomType = 'clinical' | 'reception' | 'shared' | 'triage';
export type AppointmentModality = 'telehealth' | 'in_person';
export type SessionStatus = 'queued' | 'waiting' | 'checked_in' | 'in_session' | 'complete' | 'done';
export type PaymentStatus = 'pending' | 'processing' | 'completed' | 'failed' | 'refunded';
export type OrgTier = 'core' | 'complete';

export type DerivedDisplayState =
  | 'queued'
  | 'upcoming'
  | 'late'
  | 'waiting'
  | 'checked_in'
  | 'in_session'
  | 'running_over'
  | 'complete'
  | 'done';

export interface Organisation {
  id: string;
  name: string;
  slug: string;
  tier: OrgTier;
  logo_url: string | null;
  stripe_routing: 'location' | 'clinician';
  timezone: string;
}

export interface Location {
  id: string;
  org_id: string;
  name: string;
  address: string | null;
  timezone: string;
  qr_token: string;
  stripe_account_id: string | null;
}

export interface Room {
  id: string;
  location_id: string;
  name: string;
  room_type: RoomType;
  link_token: string;
  sort_order: number;
}

export interface AppointmentType {
  id: string;
  org_id: string;
  name: string;
  modality: AppointmentModality;
  duration_minutes: number;
  default_fee_cents: number;
}

export interface Patient {
  id: string;
  org_id: string;
  first_name: string;
  last_name: string;
  date_of_birth: string | null;
}

export interface StaffAssignment {
  id: string;
  user_id: string;
  location_id: string;
  role: UserRole;
  employment_type: 'full_time' | 'part_time';
  stripe_account_id: string | null;
}

export interface User {
  id: string;
  email: string;
  full_name: string;
  avatar_url: string | null;
}

/** The flat row returned by the run sheet query, with all joins resolved. */
export interface RunsheetSession {
  // Session fields
  session_id: string;
  status: SessionStatus;
  entry_token: string;
  video_call_id: string | null;
  notification_sent: boolean;
  notification_sent_at: string | null;
  patient_arrived: boolean;
  patient_arrived_at: string | null;
  session_started_at: string | null;
  session_ended_at: string | null;
  session_created_at: string;

  // Appointment fields (nullable for on-demand sessions)
  appointment_id: string | null;
  scheduled_at: string | null;
  appointment_status: string | null;
  phone_number: string | null;

  // Appointment type
  appointment_type_id: string | null;
  type_name: string | null;
  modality: AppointmentModality | null;
  duration_minutes: number | null;
  default_fee_cents: number | null;

  // Patient
  patient_id: string | null;
  patient_first_name: string | null;
  patient_last_name: string | null;

  // Room
  room_id: string | null;
  room_name: string | null;
  room_type: RoomType | null;
  room_sort_order: number | null;

  // Clinician (assigned to appointment)
  clinician_id: string | null;
  clinician_name: string | null;

  // Payment method on file
  has_card_on_file: boolean;
  card_last_four: string | null;
  card_brand: string | null;
}

/** A RunsheetSession enriched with its derived display state. */
export interface EnrichedSession extends RunsheetSession {
  derived_state: DerivedDisplayState;
}

/** Sessions grouped by room for rendering. */
export interface RoomGroup {
  room_id: string;
  room_name: string;
  room_type: RoomType;
  room_sort_order: number;
  link_token: string;
  clinician_name: string | null;
  sessions: EnrichedSession[];
  counts: RoomCounts;
}

export interface RoomCounts {
  total: number;
  late: number;
  upcoming: number;
  waiting: number; // includes checked_in
  active: number; // in_session + running_over
  complete: number;
  done: number;
}

/** Aggregate summary across all rooms for the summary bar. */
export interface RunsheetSummary {
  total: number;
  late: number;
  upcoming: number;
  waiting: number;
  active: number;
  complete: number;
  done: number;
}

/** Badge config for a derived state. */
export interface StatusBadgeConfig {
  label: string;
  variant: 'red' | 'amber' | 'amber-soft' | 'teal' | 'teal-muted' | 'blue' | 'blue-muted' | 'gray' | 'gray-muted' | 'faded' | 'green';
}

/** Action button config for a derived state. */
export type ActionConfig = {
  label: string;
  variant: 'red' | 'amber' | 'teal' | 'blue';
  action: 'call' | 'nudge' | 'admit' | 'process';
} | null;
